import time
import os

frames = [
    "i",
    "in",
    "ini",
    "init",
    "initu",
    "initul",
    "inituli",
    "inituliz",
    "initulizi",
    "initulizin",
    "initulizing",
    "initulizing.",
    "initulizing..",
    "initulizing...",
    "initulizing..|",
    "initulizing.|",
    "initulizing|",
    "initulizin|",
    "initulizi|",
    "inituliz|",
    "inituli|",
    "initul|",
    "initu|",
    "init|",
    "ini|",
    "in|",
    "i|",
    "|",
    "",
    "L|",
    "Lo|",
    "Loa|",
    "Load|",
    "Loadi|",
    "Loadin|",
    "Loading|",
    "Loading.|",
    "Loading..|",
    "Loading...|",
    "Loading..|",
    "Loading.|",
    "Loading|",
    "Loadin|",
    "Loadi|",
    "Load|",
    "Loa|",
    "Lo|",
    "L|",
    "|",
    "",
]

while True:
    for frame in frames:
        os.system("cls" if os.name == "nt" else "clear")
        print(frame)
        time.sleep(0.05)